"""
PresenceOS - Autopilot Models (Sprint 9)
"""
import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel


class AutopilotFrequency(str, enum.Enum):
    DAILY = "daily"
    WEEKDAYS = "weekdays"
    THREE_PER_WEEK = "3_per_week"
    WEEKLY = "weekly"


class PendingPostStatus(str, enum.Enum):
    PENDING = "pending"          # Waiting for user review
    APPROVED = "approved"        # User approved via WhatsApp or dashboard
    REJECTED = "rejected"        # User rejected
    AUTO_PUBLISHED = "auto_published"  # Auto-published (no response within window)
    EXPIRED = "expired"          # Never processed


class AutopilotConfig(BaseModel):
    """Per-brand autopilot configuration."""

    __tablename__ = "autopilot_configs"

    brand_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("brands.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )

    # Activation
    is_enabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Platform targets
    platforms: Mapped[list[str] | None] = mapped_column(ARRAY(String), nullable=True)
    # Example: ["instagram", "linkedin", "tiktok"]

    # Frequency
    frequency: Mapped[AutopilotFrequency] = mapped_column(
        Enum(AutopilotFrequency),
        default=AutopilotFrequency.DAILY,
        nullable=False,
    )
    generation_hour: Mapped[int] = mapped_column(Integer, default=7, nullable=False)
    # Hour (UTC) to generate content

    # Approval settings
    auto_publish: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    # If True, publish without approval after approval_window_hours
    approval_window_hours: Mapped[int] = mapped_column(Integer, default=4, nullable=False)
    # Hours to wait for approval before auto-publishing

    # WhatsApp notification
    whatsapp_enabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    whatsapp_phone: Mapped[str | None] = mapped_column(String(20), nullable=True)
    # International format: +33612345678

    # Preferred posting time
    preferred_posting_time: Mapped[str | None] = mapped_column(
        String(5), nullable=True
    )
    # Format "HH:MM", e.g. "10:30"

    # Content topics/themes (optional)
    topics: Mapped[list[str] | None] = mapped_column(ARRAY(String), nullable=True)

    # Stats
    total_generated: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_published: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Relationships
    brand: Mapped["Brand"] = relationship("Brand", backref="autopilot_config")
    pending_posts: Mapped[list["PendingPost"]] = relationship(
        "PendingPost", back_populates="config", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<AutopilotConfig brand={self.brand_id} enabled={self.is_enabled}>"


class PendingPost(BaseModel):
    """A post generated by autopilot, waiting for approval."""

    __tablename__ = "pending_posts"

    config_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("autopilot_configs.id", ondelete="CASCADE"),
        nullable=False,
    )
    brand_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("brands.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Content
    platform: Mapped[str] = mapped_column(String(50), nullable=False)
    caption: Mapped[str] = mapped_column(Text, nullable=False)
    hashtags: Mapped[list[str] | None] = mapped_column(ARRAY(String), nullable=True)
    media_urls: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)

    # AI metadata
    ai_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    virality_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Approval flow
    status: Mapped[PendingPostStatus] = mapped_column(
        Enum(PendingPostStatus),
        default=PendingPostStatus.PENDING,
        nullable=False,
    )
    whatsapp_message_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # WhatsApp message ID for tracking callbacks

    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # When auto-publish should kick in

    # Link to scheduled post after approval
    scheduled_post_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("scheduled_posts.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Relationships
    config: Mapped["AutopilotConfig"] = relationship(
        "AutopilotConfig", back_populates="pending_posts"
    )

    def __repr__(self) -> str:
        return f"<PendingPost {self.platform} status={self.status}>"


# TYPE_CHECKING import to avoid circular
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.brand import Brand
